# Client isolation: drop L2 forwarding between LAN ports.
# Only frames to/from the router MAC are allowed.
# Generated by init script with actual br-lan MAC.
table bridge client_isolate {
	chain lan_fwd {
		type filter hook forward priority 0; policy accept;
		ether saddr __ROUTER_MAC__ accept
		ether daddr __ROUTER_MAC__ accept
		counter drop
	}
}
