#!/bin/sh /etc/rc.common
START=99
STOP=10
USE_PROCD=1

start_service() {
  /opt/proxy-manager-v1/apply_xxtouch_bypass.sh || true
  procd_open_instance
  procd_set_param command python3 /opt/proxy-manager-v1/app.py
  procd_set_param respawn
  procd_close_instance
}
